import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="bg-slate-200 dark:bg-slate-600 h-full pt-8">
      {children}
    </main>
  );
}
