import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/ui/globals.css";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Application",
  description: "Generated by create next app",
};

type ApplicationLayoutProps = {
  children: React.ReactNode;
};

export default function ApplicationLayout({
  children,
}: ApplicationLayoutProps) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={cn("h-full font-sans antialiased", fontSans.variable)}>
        {children}
      </body>
    </html>
  );
}
