import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalProviders from "./globalProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-100" suppressHydrationWarning>
      <body className={`h-full ${inter.className}`}>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
